# Gruvbox Material palette
$accent     = rgba(7daea3ff)
$cursor     = rgba(bdae91ff)
$foreground = rgba(d4be98ff)
$background = rgba(282828ff)

$color0  = rgba(3c3836ff)
$color1  = rgba(ea6962ff)
$color2  = rgba(a9b665ff)
$color3  = rgba(d8a657ff)
$color4  = rgba(7daea3ff)
$color5  = rgba(d3869bff)
$color6  = rgba(89b482ff)
$color7  = rgba(d4be98ff)
$color8  = rgba(3c3836ff)
$color9  = rgba(ea6962ff)
$color10 = rgba(a9b665ff)
$color11 = rgba(d8a657ff)
$color12 = rgba(7daea3ff)
$color13 = rgba(d3869bff)
$color14 = rgba(89b482ff)
$color15 = rgba(d4be98ff)

# Semantic mapping for hyprlock fields
$color        = $background
$inner_color  = $color0
$outer_color  = $accent
$font_color   = $foreground
$check_color  = $color2
